import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import classNames from "classnames";

import "./globals.css";
import styled from "./layout.module.css";

const inter = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={classNames(inter.className, styled.layout)}>{children}</body>
    </html>
  );
}
